### ISSUE TITLE
Call .identify() on every app start?

### ISSUE THREAD

**Issue by muscache** [amplitude/Amplitude-ReactNative#118]
Should I call `.identify()` on every app launch or does Amplitude persist identification info across restarts?

**Comment by yuhao900914** [comment]
No, you don't need to.  The identification is persist. 
And because the react-native is using amplitude native ios and android SDK, so the deviceId will be saved locally. Even if an event is sent anonymously after at least one user ID has already been seen associated with that device, Amplitude assumes the anonymous event was fired by the last known user and assigns it that user's Amplitude ID.  With the same deviceId and userId, it will have the same identification info.
