### ISSUE TITLE
trackingSessionEvents not working for Android & iOS.

### ISSUE THREAD

**Issue by ydv0121** [amplitude/Amplitude-ReactNative#120]
To track user sessions i have Enable automatically log start and end session events with `Amplitude.getInstance().trackingSessionEvents(true)` but it's not working on Android & iOS side.
i can't get the sessions events in the dashboards.

any help?

**Comment by ydv0121** [comment]
i am calling it on the entry level file of the project.is it same for both Android & iOS?
and i have to attach user_id too with the particular session.is it fine if i call the user_id event later.

**Comment by yuhao900914** [comment]
For both Android & iOS,  they are the same we need to add `trackingSessionEvents ` before initializing the SDK.
For the user_id event, do you mean identify call?

**Comment by ydv0121** [comment]
i need to set custom User ID with Amplitude.getInstance().setUserId("test_user_id") when session start and end.

**Comment by yuhao900914** [comment]
Got it, Yes, you can call the setUserId after the `trackingSessionEvents `.

**Comment by ydv0121** [comment]
so user_id will attach with the session events too right? 
like below

![Screen Shot 2022-04-25 at 11 52 11 PM](https://user-images.githubusercontent.com/37238045/165150326-561cf05e-31fd-4a08-b4f1-30d433887fb7.png)

**Comment by yuhao900914** [comment]
That's right.

**Comment by ydv0121** [comment]
Hello @yuhao900914 
i am still facing issue. not getting data of trackingSessionEvents in android.
i have set this on entry level file

amplitude.trackingSessionEvents(true);
amplitude.init('XXXX');

**Comment by ydv0121** [comment]
any possible solutions @yuhao900914 ?

**Comment by yuhao900914** [comment]
What’s your reactnative version and amplitude-reactnative version? Dose that only happens on android now? What’s your gradle version?

**Comment by ydv0121** [comment]
`react-native: 0.64.2`
`@amplitude/react-native: ^2.11.0`
`gradle:6.9`
yes its happening with android only if i fire event `ampInstance.logEvent()` then session start event triggered on Android side otherwise it doesn't work

**Comment by yuhao900914** [comment]
The session behavior is a little bit different for different Android API Levels and the session times out are also different.  What's yours? Does that fit one of the following behavior?

(https://developers.amplitude.com/docs/android#user-sessions)
`For Android API level 14 and above, a new session is created when the app comes back into the foreground after being in the background for five or more minutes or when the last event was logged (whichever occurred last). Otherwise, the background event logged will be part of the current session. Note that you can define your own session expiration time by calling setMinTimeBetweenSessionsMillis(timeout), where the timeout input is in milliseconds.

For Android API level 13 and below, foreground tracking is not available so a new session is automatically started when an event is logged 30 minutes or more after the last logged event. If another event is logged within 30 minutes, it will extend the current session. Note that you can define your own session expiration time here as well by calling setSessionTimeoutMillis(timeout), where the timeout input is in milliseconds. Also, note that enableForegroundTracking(getApplication) is still safe to call for Android API level 13 and below even though it is not available.`


And also I think you need to call `enableForegroundTracking` in order to make the session tracking more accurate. It's off by default. (https://developers.amplitude.com/docs/android#initialization) Currently, you can only enable it in the native code.

**Comment by ydv0121** [comment]
The problem is that in my case the session event not even triggered if i open my app and keep it open and use it more than 30 minutes.
should i enabled the `enableForegroundTracking` from the native side? will it help?

**Comment by yuhao900914** [comment]
@ydv0121 , if you keep the app open, it will extend that session. it will create a new session and log a session event when the app is from background to foreground and the time is more than session timeout millis. So that should be an expected behaior.

**Comment by ydv0121** [comment]
@yuhao900914, on my side i kept open my app for few hours but it won't log session event. as i explained above if i hit `ampInstance.logEvent()` then it will start logging session events. please check the attachment. if i hit the **PAGE_VIEW** event using the `logEvent` then session started but end session never called in this scenario.


![Screen Shot 2022-05-03 at 12 51 24 PM](https://user-images.githubusercontent.com/37238045/166417059-02d64d64-2d21-4cfe-9dbe-e0e51718d8a3.png)

**Comment by yuhao900914** [comment]
Hi @ydv0121,
Wrote an example app with the version you provided. It works pretty fine in Android. Can you take a look and see if that helps?  https://github.com/yuhao900914/Amplitude-RNV0642-Example 
A little bit more about the session events in android:
- For Android, we marked the app as in the background when onActivityPaused gets triggered. And treated the app as in the foreground when onActivityResumed gets triggered, where we also checked if we need to log a session event. If it's not in the same session we send the end session event and start session event.

**Comment by ydv0121** [comment]
Hey @yuhao900914 Thank you for the help in all the way and for the example too.appreciate it.
i have tried the example project which you have sent. faced the same behaviour. i have used app for while it didn't record the session event.session only started after you log event on button press.please check this image - 


![Screen Shot 2022-05-06 at 1 16 07 PM](https://user-images.githubusercontent.com/37238045/167091882-7f1cdbcb-1b3a-493f-8ec1-1c2267edd7b0.png)

**Comment by yuhao900914** [comment]
You said you use the app for a while, which means it's in the foreground all the time, right? 
So it will trigger the session event when you try to log an event. That's how it should work. 
log session event will be triggerd, when 1 [onEnterForeground](https://github.com/amplitude/Amplitude-Android/blob/main/src/main/java/com/amplitude/api/AmplitudeClient.java#L1551). 2. [when you log an event](https://github.com/amplitude/Amplitude-Android/blob/main/src/main/java/com/amplitude/api/AmplitudeClient.java#L1194). 


But curious about the issue you said before. when using the example app, did you meet the issue that there is no end session?

**Comment by ydv0121** [comment]
@yuhao900914 as you said log session event will be triggered when **onEnterForeground** but it never works on my side. on Android side when app is open or in Foreground any amount of time it never triggered a session. and as per a documentation `Amplitude.getInstance().trackingSessionEvents(true)` when i used this it will automatically log start and end session events. but it never works. it will only start the session when i hit the **logEvent()** on any **button press**.

**Comment by yuhao900914** [comment]
Going to close this comment since this question has been resolved. Feel free to reopen this if you need it.

**Comment by sabin10** [comment]
@yuhao900914 Hi, on android docs it says to call `enableForegroundTracking()` after `initialize()`
```
AmplitudeClient client = Amplitude.getInstance()
  .initialize(getApplicationContext(), "YOUR_API_KEY_HERE")
  .enableForegroundTracking(getApplication());
```
is it okay to call init() function on react-native side and enableForegroundTracking on native side?
