### ISSUE TITLE
Support React Native 0.70.x

### ISSUE THREAD

**Issue by davydspotnana** [amplitude/Amplitude-ReactNative#148]
I can't build Android:

```java
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/i/all_work/thera/mobile/node_modules/@amplitude/react-native/android/build.gradle' line: 14

* What went wrong:
A problem occurred evaluating project ':amplitude_react-native'.
> Failed to apply plugin 'com.android.internal.library'.
   > The option 'android.jetifier.blacklist' is deprecated.
     It was removed in version 7.0 of the Android Gradle plugin.
     This property has been replaced by android.jetifier.ignorelist

```

- "@amplitude/react-native": "^2.16.0",
- "react-native": "0.70.3",

**Comment by kevinpagtakhan** [comment]
Hi @davydspotnana thank you for choosing Amplitude. Since react-native@0.70 is fairly new, we have not had the time to test it against this version. I'll put in a request to the team to look into this further. To set better expectations, Amplitude rolled out a new [Analytics SDK for React Native](https://github.com/amplitude/Amplitude-TypeScript/tree/main/packages/analytics-react-native) a couple months back, which we'll provide better support moving forward.

**Comment by retyui** [comment]
@kevinpagtakhan Could you please add a warning so people who use  `rnx-dep-check` will know that is better to use alternative library


see example: https://github.com/microsoft/rnx-kit/blob/c5b9f851bf3921f7ebbb537b1016d0a364a08797/packages/dep-check/src/presets/banned.ts#L4-L9

- Docs: https://microsoft.github.io/rnx-kit/docs/tools/dep-check

**Comment by yuhao900914** [comment]
Hi @davydspotnana , 
I built a brand new rn example with `npx react-native init AwesomeProject --version 0.70.3` and install the amplitude library the same as you.  "@amplitude/react-native": "^2.16.0".

I'm thinking that issue might be caused by the Gradle and android Gradle plugin compatibility problem between your react-native project with  @amplitude/react-native.
Can you also share what's your Gradle and android Gradle plugin version? 

Provide all the versions on my worked example as a reference:
"@amplitude/react-native": "^2.16.0",
"react-native": "0.70.3",
Android Gradle Plugin: "7.2.1"
Gradle: "7.5.1"

<img width="576" alt="Screen Shot 2022-10-22 at 1 28 24 AM" src="https://user-images.githubusercontent.com/13028329/197329540-18e64052-980e-4ca8-a9e1-31f9ecf21812.png">

**Comment by retyui** [comment]
How can I find these settings above ? @yuhao900914

**Comment by yuhao900914** [comment]
@retyui 
In the Android Studio, go to File > Project Structure > Project.

**Comment by retyui** [comment]
the same ( 

@yuhao900914

<img width="717" alt="Screenshot 2022-10-26 at 23 13 04" src="https://user-images.githubusercontent.com/4661784/198139279-1bc3eaab-6743-464e-b77e-96d0ed414352.png">

**Comment by retyui** [comment]
success:
  
```tsx
> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_API_30(AVD) - 11' for :app:debug
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 51s
55 actionable tasks: 55 executed
```

**Comment by yuhao900914** [comment]
Then I think that means it's not amplitude's issue itself.  It might be some integration issue on your application.
