### ISSUE TITLE
Amplitude Logger [Error]: TypeError: Network request failed

### ISSUE THREAD

**Issue by Gakka** [amplitude/Amplitude-ReactNative#153]
Hello !
I use React Native SDK and library "@amplitude/analytics-react-native": "0.5.1", and it’s work fine for IOS, but have some problem with Android. When I try some event I have error like on screenshot `Amplitude Logger [Error]: TypeError: Network request failed. ` Event does not come to the Amplitude service 

This code below - how I initialize amplitude (Amplitude is loading normally) and call inside component . The error occurs when the button is clicked
```
await ampli.load({
    environment: 'production',
    client: {
      apiKey: apiKey,
    },
})

...


<Button onPress={() => ampli.login()} title='Login' />
```

Could you please help me to find what might be wrong?
![IMG_0179](https://user-images.githubusercontent.com/12518604/202145189-8660c4ff-7c75-4a3c-900b-b638d5fb7e73.JPG)

**Comment by bohan-amplitude** [comment]
Hi @Gakka ,

Thank you for your information. Based on the log message the problem is likely related to network access. Do you test applications on emulator or real phone device. Checking network permissions of android system. And If you can provide more details about the error exception and sample code snippet that related to the error, will help us finding possible cause.

**Comment by liuyang1520** [comment]
Hi @Gakka , thank you for supporting us!

This repo is the lagacy react-native SDK, I think you are using the new react-native SDK (@amplitude/analytics-react-native). If the issue persists after checking the network permissions in Android system, please create an issue in https://github.com/amplitude/Amplitude-TypeScript/issues.

Thanks!
