### ISSUE TITLE
`amplitude-react-native` depends upon `React-Core`, which does not define modules

### ISSUE THREAD

**Issue by payucads** [amplitude/Amplitude-ReactNative#54]
Hi,

I'm receiving this error even after doing everything from the #46.

<img width="1394" alt="Screenshot 2021-03-22 at 12 20 33" src="https://user-images.githubusercontent.com/30795120/111982408-38de6e80-8b09-11eb-8950-570eafa38f80.png">

I've done all of these:
`pod repo update && pod install
pod install --repo update
pod update amplitude-react-native && pod update Amplitude
pod cache clean --all && pod install`

When that didn't work, I deleted the Pods folder and Podfile.lock and then reinstalled them, but I'm still running into this same error.

If I try to set the use_modular_headers! in my Podfile, it breaks other packages. Do you have any idea how to fix this error?

**Comment by kelsonpw** [comment]
Hey payucads.  This is caused by the version of react native not having native swift support.  I've seen this exact error and the solution does involve use_modular_headers, just needs to be turned off for certain pods.

I've laid out the solution [here](https://github.com/amplitude/Amplitude-ReactNative/issues/52#issuecomment-803857119)


Let me know if this is still causing you problems after trying what I've linked

**Comment by payucads** [comment]
@kelsonpw thank you buddy! you're a lifesaver 😄

**Comment by kelsonpw** [comment]
@payucads not a problem at all!  It's important to me that people are able to use this library without talk much effort even if they have an older RN version.   Any chance you'd be willing to share what versions youre project is on?

**Comment by zeulb** [comment]
@kelsonpw I'm on RN 0.63 but I'm getting the same error. I can't enable use_modular_module! globally because glog, Folly, and DoubleConversion are defined in `require_relative '../node_modules/react-native/scripts/react_native_pods'` now. Any idea why this is still happening on v0.63?
