### ISSUE TITLE
TypeError: null is not an object (evaluating 'AmplitudeReactNative.setLibraryName')

### ISSUE THREAD

**Issue by sathishramnath** [amplitude/Amplitude-ReactNative#89]
Amplitude.getInstance().logEvent('BUTTON_CLICKED'); - throws above error.

**Comment by yuhao900914** [comment]
Hi @sathishramnath, 
Is this an expo project? We have had the same issue previously. Unfortunately, we don't support the Expo project. And Expo-managed projects do not support packages with native code (like this). You can install expo-analytics-amplitude for using amplitude react native. 
https://github.com/amplitude/Amplitude-ReactNative/issues/69

**Comment by pierrezimmermannbam** [comment]
Hi @yuhao900914 I'm getting the same error. I'm not using expo-analytics-amplitude because it is deprecated in favor of this repo because expo now supports packages with native code through the use of expo-dev-client, it should work in this case no ? Not sure what the impact of this warning is though because logEvent seems to work fine

**Comment by yuhao900914** [comment]
Hi @pierrezimmermannbam, thanks for using amplitude. 
This react native not support expo. However, we have a new react-native SDK which has expo support. Please head up to https://github.com/amplitude/Amplitude-TypeScript/tree/main/packages/analytics-react-native

**Comment by pierrezimmermannbam** [comment]
Oh ok thanks! It says it's still in beta though, is it safe to use in production ?
